const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const prototypeRoot = path.resolve(__dirname, '../..');
const prototypeFolder = path.basename(prototypeRoot);

const base = process.env.PROTOTYPE_URL || `http://127.0.0.1:8767/${prototypeFolder}/mahjong-game-standalone.html`;
const results = [];
async function test(name, run) {
  if (process.env.TEST_FILTER && !name.includes(process.env.TEST_FILTER)) return;
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1024 } });
  const page = await context.newPage();
  page.setDefaultTimeout(3000);
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  try {
    await page.goto(base);
    await run(page, context);
    assert.deepEqual(errors, [], "No uncaught browser errors");
    results.push({ name, passed: true });
    console.log('PASS', name);
  } catch (error) {
    results.push({ name, passed: false, error: error.message });
    console.log('FAIL', name, error.message.split('\n')[0]);
  } finally { await browser.close(); }
}

(async () => {
  await test('Avatar selection applies immediately and locked avatars preserve selection', async (page) => {
    await page.getByRole('button', { name: 'View your profile', exact: true }).first().click();
    assert.equal(await page.locator('#cms-profile').isVisible(), true);
    assert.equal(await page.locator('#cms-settings').isVisible(), false);
    await page.getByRole('button', { name: 'Close player profile', exact: true }).click();
    assert.equal(await page.locator('.cm-settings-stack .cm-dropdown-field').count(), 0);
    const headerSettings=page.locator('.cm-balance-pill__actions #cms-header-settings');
    assert.equal(await headerSettings.isVisible(), true);
    await headerSettings.click();
    await page.getByRole('button', { name: 'Select ANIMAL avatar 2', exact: true }).click();
    assert.equal(await page.locator('#player-info-0 .cms-avatar-face').getAttribute('src'), 'support/coinpoker_assets/avatars/avatar-2.webp');
    await page.getByRole('button', { name: 'Select 3-BET CLUB avatar 2001', exact: true }).click();
    assert.equal(await page.locator('#cms-member-dialog').isVisible(), true);
    assert.equal(await page.locator('#player-info-0 .cms-avatar-face').getAttribute('src'), 'support/coinpoker_assets/avatars/avatar-2.webp');
    await page.getByRole('button', { name: 'Got it', exact: true }).click();
    await page.getByRole('button', { name: 'Close settings', exact: true }).click();
    await page.reload();
    await page.waitForSelector('#player-info-0 .cms-avatar-face');
    assert.equal(await page.locator('#player-info-0 .cms-avatar-face').getAttribute('src'), 'support/coinpoker_assets/avatars/avatar-2.webp');
  });
  await test('Emotes update unique recents and throwables travel to the selected seat', async page => {
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.getByRole('button', { name: 'Play Dode to Moon', exact: true }).click();
    await page.waitForSelector('.cms-effect[data-asset="65"] svg');
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.getByRole('tab', { name: 'Recents', exact: true }).click();
    assert.equal(await page.locator('#cms-picker-grid [data-asset]').count(), 1);
    await page.getByRole('button', { name: 'Play Dode to Moon', exact: true }).click();
    await page.locator('#player-info-2 [data-social-player]').click();
    assert.match(await page.locator('#cms-picker-title').textContent(), /gdPdg/);
    await page.locator('#cms-picker-grid [data-asset="119"]').click();
    await page.waitForSelector('.cms-effect[data-asset="119"][data-target="2"] svg');
    assert.equal(await page.locator('#cms-picker').isVisible(), false);
  });
  await test('Chat rejects blank input, sends, replies, tags and respects bubble settings', async page => {
    await page.getByRole('button', { name: 'Open table chat', exact: true }).click();
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('   ');
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).press('Enter');
    assert.equal(await page.locator('#cms-messages .cms-message').count(), 0);
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('Hello table');
    await page.getByRole('button', { name: 'Send message', exact: true }).click();
    await page.waitForSelector('#cms-messages .cms-message');
    assert.equal(await page.locator('.cms-message-text').last().textContent(), 'Hello table');
    await page.getByRole('button', { name: 'Message actions', exact: true }).last().click();
    await page.getByRole('button', { name: 'Reply', exact: true }).last().click();
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('Reply text');
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).press('Enter');
    await page.waitForSelector('.cms-message-quote');
    assert.match(await page.locator('.cms-message-quote').last().textContent(), /Hello table/);
    await page.getByRole('button', { name: 'Mention a player', exact: true }).click();
    await page.getByRole('button', { name: '@gdPdg', exact: true }).click();
    assert.equal(await page.getByRole('textbox', { name: 'Chat message', exact: true }).inputValue(), '@gdPdg ');
    await page.getByRole('button', { name: 'Chat options', exact: true }).click();
    await page.getByLabel('Hide chat bubbles', { exact:true }).check();
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('No bubble');
    await page.getByRole('textbox', { name: 'Chat message', exact: true }).press('Enter');
    await page.waitForFunction(() => document.querySelector('#cms-messages').textContent.includes('No bubble'));
    assert.equal(await page.locator('.cms-bubble').count(), 0);
  });
  await test('Membership changes unlock assets and synchronize every own avatar', async page => {
    await page.waitForSelector('#player-info-0 .cms-avatar-ring');
    const previewRing=await page.locator('#player-info-0 .cms-avatar-ring').getAttribute('src');
    await page.locator('#cms-demo summary').click();
    await page.locator('#cms-demo [data-demo-member]').check();
    await page.getByRole('button', { name:'Settings',exact:true }).click();
    await page.getByRole('button', { name:'Select 3-BET CLUB avatar 2001',exact:true }).click();
    assert.equal(await page.locator('#cms-member-dialog').isVisible(),false);
    assert.equal(await page.locator('#player-info-0 .cms-avatar-ring').getAttribute('src'),previewRing);
    assert.match(await page.locator('.cms-avatar-preview').innerText(),/3-Bet Club member/);
    assert.match(await page.locator('.cm-center-indicator__plate--bottom img').getAttribute('src'),/2001/);
    await page.waitForFunction(()=>[...document.querySelectorAll('#cms-settings img')].every(i=>i.complete&&i.naturalWidth));
    assert.equal(await page.locator('[data-avatar]').count(),51);
    await page.getByRole('button', { name:'Close settings',exact:true }).click();
    await page.locator('#cms-demo [data-demo-member]').uncheck();
    assert.equal(await page.locator('#player-info-0 .cms-avatar-face').getAttribute('src'),'support/coinpoker_assets/avatars/avatar-1.webp');
  });
  await test('Recents keep ten unique emotes in last-used order', async page => {
    for(let id=56;id<=65;id++) {
      await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
      await page.locator(`#cms-picker-grid [data-asset="${id}"]`).click();
    }
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.getByRole('tab',{name:'Penguin',exact:true}).click();
    await page.locator('#cms-picker-grid [data-asset="41"]').click();
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.getByRole('tab',{name:'Recents',exact:true}).click();
    assert.deepEqual(await page.locator('#cms-picker-grid [data-asset]').evaluateAll(xs=>xs.map(x=>Number(x.dataset.asset))),[41,65,64,63,62,61,60,59,58,57]);
    await page.locator('#cms-picker-grid [data-asset="60"]').click();
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    assert.equal(await page.locator('#cms-picker-grid [data-asset]').count(),10);
    assert.equal(await page.locator('#cms-picker-grid [data-asset]').first().getAttribute('data-asset'),'60');
  });
  await test('Chat mute options filter incoming events but preserve own messages', async page => {
    await page.getByRole('button',{name:'Open table chat',exact:true}).click();
    await page.getByRole('button',{name:'Chat options',exact:true}).click();
    await page.getByLabel('Mute spectator chat',{exact:true}).check();
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveChat({text:'Spectator text',spectator:true})),false);
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveChat({from:1,text:'Seated player'})),true);
    await page.getByLabel('Mute all chats',{exact:true}).check();
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveChat({from:1,text:'Muted text'})),false);
    await page.getByRole('textbox',{name:'Chat message',exact:true}).fill('My message still works');
    await page.getByRole('textbox',{name:'Chat message',exact:true}).press('Enter');
    await page.waitForFunction(()=>document.querySelectorAll('.cms-message').length===2);
    assert.equal(await page.locator('.cms-message-text').last().textContent(),'My message still works');
  });
  await test('Quick messages send directly, copy works, errors preserve the draft', async (page,context) => {
    await context.grantPermissions(['clipboard-read','clipboard-write']);
    await page.getByRole('button',{name:'Open table chat',exact:true}).click();
    await page.locator('.cms-quick-row [data-quick="GG 👍"]').click();
    await page.waitForSelector('.cms-message');
    assert.equal(await page.locator('.cms-message-text').textContent(),'GG 👍');
    await page.locator('.cms-message').hover();
    await page.getByRole('button',{name:'Message actions',exact:true}).click();
    await page.getByRole('button',{name:'Copy',exact:true}).click();
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'GG 👍');
    await page.locator('#cms-demo summary').click();
    await page.locator('#cms-demo [data-demo="error"]').click();
    await page.getByRole('textbox',{name:'Chat message',exact:true}).fill('Keep my draft');
    await page.getByRole('textbox',{name:'Chat message',exact:true}).press('Enter');
    await page.waitForSelector('#cms-chat-error:not([hidden])');
    assert.equal(await page.getByRole('textbox',{name:'Chat message',exact:true}).inputValue(),'Keep my draft');
    await page.getByRole('textbox',{name:'Chat message',exact:true}).press('Enter');
    await page.waitForFunction(()=>document.querySelectorAll('.cms-message').length===2);
    assert.equal(await page.locator('#cms-chat-error').isVisible(),false);
  });
  await test('Three-player and waiting tables expose only occupied targets', async page => {
    await page.goto(base+'?table=kansai-full-b1');
    await page.waitForSelector('#cms-ui[data-ready="true"]',{state:'attached'});
    assert.equal(await page.locator('.cms-seat').count(),3);
    assert.equal(await page.locator('.cms-seat[data-player="3"]').count(),0);
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.setPlayerActive(3,true)),false);
    await page.goto(base+'?table=japanese-east-b1');
    await page.waitForSelector('#cms-ui[data-ready="true"]',{state:'attached'});
    assert.equal(await page.locator('.cms-seat').count(),3);
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveThrowable({id:119,from:1,to:3})),false);
    assert.equal(await page.locator('#player-info-3').evaluate(el=>el.inert),true);
    assert.equal(await page.locator('#waiting-text').isVisible(),true);
  });
  await test('Throwables reach the selected seat and stop when a participant leaves', async page => {
    await page.waitForSelector('#cms-ui[data-ready="true"]',{state:'attached'});
    await page.evaluate(()=>CoinMahjongSocial.receiveThrowable({id:119,from:1,to:2}));
    await page.waitForFunction(()=>{const e=document.querySelector('.cms-effect[data-target="2"]'),seat=document.querySelector('.cms-seat[data-player="2"]');return e&&Math.abs(parseFloat(e.style.left)-seat.offsetLeft)<1;});
    assert.equal(await page.locator('.cms-effect[data-target="2"] svg').count(),1);
    await page.evaluate(()=>CoinMahjongSocial.setPlayerActive(2,false));
    assert.equal(await page.locator('.cms-effect').count(),0);
    assert.equal(await page.locator('.cms-seat[data-player="2"]').count(),0);
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveThrowable({id:119,from:1,to:2})),false);
  });
  await test('Reduced motion and failed animation loads retain a usable preview', async page => {
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.locator('#cms-picker-grid [data-asset="56"]').click();
    await page.waitForSelector('.cms-effect img');
    assert.equal(await page.locator('.cms-effect svg').count(),0);
    await page.emulateMedia({reducedMotion:'no-preference'});
    await page.route('**/emotes/animations/57_*.json',route=>route.abort());
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.locator('#cms-picker-grid [data-asset="57"]').click();
    await page.waitForSelector('.cms-effect[data-asset="57"] img');
    assert.match(await page.locator('#cms-toast').textContent(),/Animation unavailable/);
  });
  await test('Mobile controls stay inside the table and keep chat operable', async page => {
    await page.setViewportSize({width:390,height:844});
    await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
    const tableBounds=await page.locator('#mjg-stage').boundingBox();
    const insideTable=r=>r&&r.x>=tableBounds.x&&r.x+r.width<=tableBounds.x+tableBounds.width+1&&r.y>=tableBounds.y&&r.y+r.height<=tableBounds.y+tableBounds.height+1;
    const settingsEntry=page.locator('.cms-window-header #cms-mobile-settings');
    const entryBounds=await settingsEntry.boundingBox();
    assert.ok(insideTable(entryBounds)&&entryBounds.y<tableBounds.y+80);
    assert.ok(insideTable(await page.locator('#cms-chat-toggle').boundingBox()));
    assert.equal(await page.locator('#cms-header-settings').isVisible(), false);
    assert.equal(await page.locator('.cms-toolbar #cms-mobile-settings').count(), 0);
    await settingsEntry.click();
    let r=await page.locator('#cms-settings').boundingBox();
    assert.ok(insideTable(r));
    await page.getByRole('button',{name:'Close settings',exact:true}).click();
    await page.locator('#cms-mobile-players').click();
    await page.locator('#cms-players-list [data-social-player="0"]').click();
    r=await page.locator('#cms-picker').boundingBox();
    assert.ok(insideTable(r));
    await page.getByRole('button',{name:'Close emotes',exact:true}).click();
    await page.getByRole('button',{name:'Open table chat',exact:true}).click();
    await page.getByRole('textbox',{name:'Chat message',exact:true}).fill('<img src=x onerror=alert(1)>');
    await page.getByRole('textbox',{name:'Chat message',exact:true}).press('Enter');
    await page.waitForSelector('.cms-message');
    assert.equal(await page.locator('.cms-message-text img').count(),0);
    assert.equal(await page.locator('.cms-message-text').textContent(),'<img src=x onerror=alert(1)>');
    r=await page.locator('#cms-chat').boundingBox();
    assert.ok(insideTable(r));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  });
  await test('Avatar hover cancels on exit and disabled throwables do not open or play', async page => {
    await page.waitForSelector('#cms-ui[data-ready="true"]',{state:'attached'});
    const avatar=page.locator('#player-info-1 [data-social-player]');
    await avatar.hover();await page.mouse.move(400,30);await page.waitForTimeout(240);
    assert.equal(await page.locator('#cms-picker').isVisible(),false);
    await avatar.hover();await page.waitForTimeout(240);
    assert.equal(await page.locator('#cms-picker').isVisible(),true);
    await page.mouse.move(400,30);await page.waitForTimeout(360);
    assert.equal(await page.locator('#cms-picker').isVisible(),false);
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.getByRole('tab',{name:'Interactions',exact:true}).click();
    assert.equal(await page.getByLabel('Show throwables on hover').count(),0);
    await page.getByLabel('Enable throwables').uncheck();
    await page.getByRole('button',{name:'Close settings',exact:true}).click();
    await avatar.hover();await page.waitForTimeout(240);
    assert.equal(await page.locator('#cms-picker').isVisible(),false);
    assert.equal(await page.evaluate(()=>CoinMahjongSocial.receiveThrowable({id:119,from:1,to:0})),false);
    assert.equal(await page.locator('.cms-effect').count(),0);
  });
  await test('Both avatar areas open the matching picker and list profile buttons preserve winds', async page => {
    await page.waitForSelector('#cms-ui[data-ready="true"]',{state:'attached'});
    assert.equal(await page.locator('.cms-seat-action,.cms-row-throw,#cms-self-emote,#cms-mobile-emote,[data-throw]').count(),0);
    for(const area of ['seat','list'])for(let id=0;id<4;id++){
      const scope=area==='seat'?`.cms-seat[data-player="${id}"]`:`#player-info-${id}`;
      const avatar=page.locator(scope+' [data-social-player]');
      await avatar.hover();
      await page.waitForFunction(()=>!document.querySelector('#cms-picker').hidden);
      assert.equal(await page.locator('#cms-picker').getAttribute('data-kind'),id===0?'emote':'throw');
      assert.equal(await page.locator('#cms-profile').isVisible(),false);
      assert.equal(await avatar.getAttribute('aria-expanded'),'true');
      if(id!==0)assert.match(await page.locator('#cms-picker-title').textContent(),new RegExp(await page.locator(`#player-info-${id} .cm-player-row__name`).textContent()));
      const inside=await page.evaluate(()=>{const a=document.querySelector('#mjg-stage').getBoundingClientRect(),b=document.querySelector('#cms-picker').getBoundingClientRect();return b.left>=a.left&&b.top>=a.top&&b.right<=a.right+1&&b.bottom<=a.bottom+1;});
      assert.equal(inside,true);
      await page.keyboard.press('Escape');
    }
    for(let id=0;id<4;id++){
      const row=page.locator(`#player-info-${id}`),button=row.locator('[data-profile]');
      assert.equal(await button.evaluate(el=>el.nextElementSibling.classList.contains('cm-wind-tile')),true);
      assert.equal(await row.locator('.cm-wind-tile').textContent(),['東','南','西','北'][id]);
      await button.click();
      assert.equal(await page.locator('#cms-profile-title').textContent(),'Profile');
      assert.equal(await page.locator('#cms-profile h3').textContent(),await row.locator('.cm-player-row__name').textContent());
      await page.getByRole('button',{name:'Close player profile',exact:true}).click();
    }
  });
  await test('Hover menus remain usable across the gap and support keyboard and touch entry', async (page,context) => {
    const avatar=page.locator('#player-info-0 [data-social-player]');
    await avatar.hover();await page.waitForTimeout(240);
    assert.equal(await page.locator('#cms-picker').isVisible(),true);
    await page.locator('#cms-picker-grid').hover();await page.waitForTimeout(360);
    assert.equal(await page.locator('#cms-picker').isVisible(),true);
    await page.locator('#cms-picker-grid [data-asset="56"]').click();
    await page.waitForSelector('.cms-effect[data-asset="56"]');
    assert.equal(await page.locator('#cms-picker').isVisible(),false);
    await avatar.focus();await page.keyboard.press('Enter');
    assert.equal(await page.locator('#cms-picker').isVisible(),true);
    await page.keyboard.press('Escape');
    assert.equal(await avatar.evaluate(el=>el===document.activeElement),true);
    const touchContext=await context.browser().newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
    const touch=await touchContext.newPage();await touch.goto(base);
    await touch.locator('#cms-mobile-players').tap();
    await touch.locator('#cms-players-list [data-social-player="0"]').tap();
    assert.equal(await touch.locator('#cms-picker').getAttribute('data-kind'),'emote');
    await touch.locator('#cms-picker-close').tap();
    await touch.locator('#cms-mobile-players').tap();
    await touch.locator('#cms-players-list [data-social-player="2"]').tap();
    assert.equal(await touch.locator('#cms-picker').getAttribute('data-kind'),'throw');
    await touch.locator('#cms-picker-grid [data-asset="119"]').tap();
    await touch.waitForSelector('.cms-effect[data-target="2"]');
    await touchContext.close();
  });
  await test('Emoji sound loads its mapped clip and stops requesting clips when muted', async page => {
    const audio=[];
    page.on('response',response=>{if(response.url().endsWith('.wav'))audio.push({url:response.url(),status:response.status()});});
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.getByRole('tab',{name:'Chips',exact:true}).click();
    const clipLoaded=page.waitForResponse(response=>response.url().endsWith('48_chip4.wav'));
    await page.locator('#cms-picker-grid [data-asset="48"]').click();
    await clipLoaded;
    assert.ok(audio.some(r=>r.status===200));
    await page.getByRole('button',{name:'Settings',exact:true}).click();
    await page.getByRole('tab',{name:'Interactions',exact:true}).click();
    await page.getByLabel('Emoji Playing').uncheck();
    await page.getByRole('button',{name:'Close settings',exact:true}).click();
    await page.locator('.cms-seat[data-player="0"] [data-social-player]').click();
    await page.locator('#cms-picker-grid [data-asset="49"]').click();
    await page.waitForSelector('.cms-effect[data-asset="49"] svg');
    await page.waitForTimeout(150);
    assert.equal(audio.some(r=>r.url.endsWith('49_chip5.wav')),false);
  });
  if (process.env.RESULT_PATH) fs.writeFileSync(process.env.RESULT_PATH, JSON.stringify({checked_at:new Date().toISOString(),browser:'Chrome via Playwright',base,prototype_folder:prototypeFolder,source_sha256:Object.fromEntries(['support/prototype/social.js','support/prototype/social.css','mahjong-game-standalone.html'].map(file=>[file,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.join(prototypeRoot,file))).digest('hex')])),results}, null, 2)+'\n');
  if (results.some(result => !result.passed)) process.exitCode = 1;
})();
